import React from 'react'
import { mount } from 'enzyme'

import Label from '../../src/Label'
import Form from '../../src/Form'

function mountForm(content) {
  return mount(<Form name="myForm" action="/action" method="POST">{content}</Form>)
}

describe('Label', () => {
  it('should render a <label> element', () => {
    const wrapper = mountForm(<Label name="val" />)
    expect(wrapper.find('label').length).to.equal(1)
  })

  it('should render children', () => {
    const label = mountForm(<Label name="val">Hello</Label>).find('label')
    expect(label.text()).to.equal('Hello')
  })

  it('should set an autogenerated htmlFor attribute based on the name prop', () => {
    const input = mountForm(<Label name="myInput" />).find('label')
    expect(input.prop('htmlFor')).to.equal('myForm_myInput')
  })

  it('should pass on any props', () => {
    const input = mountForm(<Label name="val" className="fancy" />).find('label')
    expect(input.prop('className')).to.equal('fancy')
  })
})
