import React from 'react'
import { mount } from 'enzyme'

import Textarea from '../../src/Textarea'
import Form from '../../src/Form'

function mountForm(children) {
  return mount(<Form name="myForm" action="/action" method="POST">{children}</Form>)
}

describe('Textarea', () => {
  it('should render a <textarea> element', () => {
    const wrapper = mountForm(<Textarea name="val" />)
    expect(wrapper.find('textarea').length).to.equal(1)
  })

  it('should be empty by default', () => {
    const textarea = mountForm(<Textarea name="val" />).find('textarea')
    expect(textarea.prop('value')).to.equal('')
  })

  it('should set the initial value as textarea value', () => {
    const textarea = mountForm(<Textarea name="val" initial="Init" />).find('textarea')
    expect(textarea.prop('value')).to.equal('Init')
  })

  it('should receive an autogenerated ID by default', () => {
    const textarea = mountForm(<Textarea name="myTextarea" />).find('textarea')
    expect(textarea.prop('id')).to.equal('myForm_myTextarea')
  })

  it('should pass on any props, overriding the autogenerated ID', () => {
    const textarea = mountForm(<Textarea name="val" id="myTextarea" className="fancy" />).find('textarea')
    expect(textarea.prop('id')).to.be.equal('myTextarea')
    expect(textarea.prop('className')).to.equal('fancy')
  })

  describe('when entering data', () => {
    it('should update its value, replacing the initial value', () => {
      const textarea = mountForm(<Textarea name="val" initial="Init" />).find('textarea')
      textarea.simulate('change', { target: { value: 'Hello' } })
      expect(textarea.prop('value')).to.equal('Hello')
    })

    it('should trigger the onChange handler', () => {
      const onChange = sinon.spy()
      const textarea = mountForm(<Textarea name="val" onChange={onChange} />).find('textarea')
      textarea.simulate('change', { target: { value: 'Hello' } })
      expect(onChange).to.have.been.called()
    })
  })
})
